### ISSUE TITLE
Cannot find module, custom handlers

### ISSUE THREAD

**Issue by dweber019** [kevinrenskers/raml2html#96]
I try to convert a raml to html with a custom template.handlebar like so:
```bash
raml2html -t templates/api-template.handlebars -i raml/sms.raml -o sms.html
```

the following error will be thrown:
```bash
module.js:340
    throw err;
          ^
Error: Cannot find module 'templates/api-template.handlebars'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at getDefaultConfig (/usr/local/lib/node_modules/raml2html/lib/raml2html.js:90:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/raml2html/lib/raml2html.js:148:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I have installed the raml2html module globally and run the command in a folder somewhere.

Can you help to resolve this issue?

Best & thx
Dave

**Comment by kevinrenskers** [comment]
There was a bug in the parsing of the path, it should now work if you run it in the folder containing the templates and prefix the path with `./`.

`raml2html -t ./template.handlebars -i example.raml`

An update is coming soon that should make this easier (no need for `./`, can use remote urls).

**Comment by kevinrenskers** [comment]
1.1.0 has been released

**Comment by dweber019** [comment]
I have tested version 1.1.0.
It's fully working for me with ./ and without.
Thanks a lot for your work
